---
sudo: required
# 10.11 (see https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version)
os: osx

before_install:
  - brew update && brew upgrade

install:
  # Install pip.
  - sudo easy_install pip

  # Install Ansible.
  - sudo pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Add a hosts file.
  - sudo mkdir -p /etc/ansible
  - sudo touch /etc/ansible/hosts
  - "echo -e '[local]\nlocalhost ansible_connection=local' | sudo tee -a /etc/ansible/hosts > /dev/null"

  # Add conf directory (this is an hack to pass the build)
  # OhMyZsh setup looks for conf directory
  - sudo mkdir -p conf

script:
  # Install dependencies.
  # - "ansible-galaxy install -r requirements.yml"

  # Check the role/playbook's syntax.
  - "ansible-playbook quick_start.yml --syntax-check"

  # Test the playbook.
  - "travis_wait 90 ansible-playbook --extra-vars '{\"configure_sudoers\":\"false\"}' quick_start.yml"

  # Test the playbook's idempotence.
  # Note that there would be 18 tasks shown as changed
  # - idempotence=$(mktemp)
  # - yes | "ansible-playbook --extra-vars '{\"configure_sudoers\":\"false\"}' quick_start.yml | tee -a ${idempotence}"
  # - >
  #   tail ${idempotence}
  #   | grep -q 'changed=18.*failed=0'
  #   && (echo 'Idempotence test: pass' && exit 0)
  #   || (echo 'Idempotence test: fail' && exit 1)

  #checking for 3 changed notifications due to some wierd thing for wakatime vs code plugin, 2 other chnages are related to zshrc
