---
homebrew_installed_packages:
  - autoconf
  - bash-completion
  - git
  - go
  - node
  - nvm
  - wget

homebrew_uninstalled_packages:

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - firefox
  - google-chrome
  - vagrant
  # - virtualbox

homebrew_cask_uninstalled_apps:

