---
- name: Check if Homebrew is already installed
  stat:
    path: /usr/local/bin/brew
  register: brew

- name: Install homebrew
  script: install-homebrew.sh
  when: not brew.stat.exists
  args:
    creates: /usr/local/bin/brew

- name: Doctor Homebrew
  command: /usr/local/bin/brew doctor
  failed_when: '"Warning: Homebrew's bin was not found in your PATH." not in brew_health.stderr'
  register: brew_health

- name: Up[date/grade] Homebrew
  command: /usr/local/bin/brew update && brew upgrade

- name: Homebrew Cask
  command: /usr/local/bin/brew install caskroom/cask/brew-cask

# - name: Install Packages with Homebrew