---
- name: Check if Homebrew is already installed
  stat:
    path: /usr/local/bin/brew
  register: brew

- name: Install homebrew
  script: install-homebrew.sh
  when: not brew.stat.exists
  args:
    creates: /usr/local/bin/brew

- name: Doctor Homebrew
  shell: brew doctor
  register: brew_health

- name: Up[date/grade] Homebrew
  shell: brew update && brew upgrade

- name: Homebrew Cask
  shell: brew install caskroom/cask/brew-cask

# - name: Install Packages with Homebrew