---
- name: Check for Visual Studio Code
  stat:
    path: /Applications/Visual Studio Code.app/
  register: vscode

- name: Unpack Visual Studio Code
  unarchive:
    src: https://go.microsoft.com/fwlink/?LinkID=620882
    dest: /Applications
    remote_src: yes
  when: not vscode.stat.exists

# - name: Install VSCode Extensions